= Jenkins Bots
The Jenkins project uses multiple bots account for various needs.
This document is a non exhaustive list of them.

== Github

=== jenkins-release-bot

owner: link:https://github.com/olblak(Olblak)
link:https://github.com/jenkins-release-bot(Profile)

This bot is used to automate any tasks related to releases that need Github integration

Ex:
* Release jenkinsci/jenkins
* Release jenkinsci/remoting
* Used from release.ci.jenkins.io


=== jenkins-infra-bot

owner: link:https://github.com/olblak(Olblak)
link:https://github.com/jenkins-infra-bot(Profile)

This bot is used to for various infrastructure task that required Github integration
ex:
- pluginsite configuration

=== jenkinsadmin

This bots is the first github bot used in the Jenkins Infrastructure

owner: link:https://github.com/kohsuke(Kohsuke)
link: https://github.com/jenkinsadmin/(jenkinsadmin)

exemple:
* Automatically open pull request
* jenkinsadmin irc bot

Remark: We don't have access to this bot anynmore and we need Kohsuke to transfer the ownership
