= Jenkins on Jenkins

This document covers the services available on
link:https://ci.jenkins.io[ci.jenkins.io]
and our internal `trusted.ci` instance.


=== Node Labels

We use node labels to define capabilities of the nodes in our Jenkins clusters. These are conventional and are to be used
when referencing nodes, e.g. in the `Jenkinsfile`.

* `linux` \ `docker` (alias of `java`): A Linux (Ubuntu 20.04 LTS) instance with Docker Engine Community Edition
** On AWS (label `aws`): https://github.com/jenkins-infra/jenkins-infra/blob/production/hieradata/clients/azure.ci.jenkins.io.yaml#L121[]
** On Azure: https://github.com/jenkins-infra/jenkins-infra/blob/production/hieradata/clients/azure.ci.jenkins.io.yaml#L172[] 
* `windows` : A Windows 2019 instance with 4vCPU/16GB RAM provisioned (link:https://azure.microsoft.com/en-us/documentation/articles/cloud-services-sizes-specs/[Standard_D4s_v3] on Azure or link:https://aws.amazon.com/en/ec2/instance-types/[T3Xlarge] on AWS)
* `highmem` : A Linux (Ubuntu 20.04 LTS) instance with 16vCPU/64GB RAM
(link:https://azure.microsoft.com/en-us/documentation/articles/cloud-services-sizes-specs/[Standard_D16s_v3] on Azure or link:https://aws.amazon.com/en/ec2/instance-types/[M54xlarge] on AWS). Please avoid unless running ATH or other high-memory capacity instances.
* `docker-highmem` : A Linux (Ubuntu 20.04 LTS) instance with 16vCPU/64GB RAM and a running Docker daemon
(link:https://azure.microsoft.com/en-us/documentation/articles/cloud-services-sizes-specs/[Standard_D16s_v3] on Azure or link:https://aws.amazon.com/en/ec2/instance-types/[M54xlarge] on AWS). Please avoid unless running ATH or other high-memory capacity instances.
* `arm64docker` : An ARM64 Linux (Ubuntu 20.04 LTS) instance with 4vCPU/16GB RAM and a running Docker daemon
(link:https://aws.amazon.com/en/ec2/instance-types/[A1Xlarge] on AWS)
* `docker-windows` : A Windows 2019 instance with 4vCPU/16GB RAM provisioned (link:https://azure.microsoft.com/en-us/documentation/articles/cloud-services-sizes-specs/[Standard_D4s_v3] on Azure or link:https://aws.amazon.com/en/ec2/instance-types/[T3Xlarge] on AWS) that is able to run Windows Docker images

==== Node Labels - Processors

* `amd64` : An agent running an AMD or Intel 64 bit processor
* `arm64` : An agent running an ARM 64 bit processor on AWS (Amazon Graviton)
* `s390x` : An agent running an IBM System 390x (Z series) processor

==== Container Agents

We use link:https://plugins.jenkins.io/kubernetes/[Kubernetes Agents] with a set of different kubernetes clusters to execute container based agents.
Currently it is only available on ci.jenkins.io, and not yet on trusted.ci or cert.ci.

The agent images are all built from the link:https://github.com/jenkins-infra/docker-inbound-agents[jenkins-infra/docker-inbound-agents] repository.

To use a container agent, specify one of the following labels:

* `maven`: A Maven 3 (Debian) container with JDK8
* `maven-windows`: A maven 3 Windows container with JDK8
* `maven-11`: A maven 3 (Debian) container with JDK11
* `maven-11-windows`: A maven 3 Windows container with JDK11
* `maven-17`: A maven 3 (Debian) container with JDK17
* `maven-17-windows`: A maven 3 Windows container with JDK17
* `maven-19`: A maven 3 (Debian) container with JDK19
* `maven-19-windows`: A maven 3 Windows container with JDK19
* `node`: A Node (Alpine) container
* `ruby` :  A Ruby 2 (Debian) container
* `alpine` : An Alpine-based container with no additional tooling.

Please note that it is not recommended to use the pipeline instructions specific to Kubernetes (such as `podTemplate()` or `agent { kubernetes {}}}` unless you really need it (e.g. if the default set of container agent templates does not fit your needs).
The reason is related to the ability of quickly moving the workload to another kind of agents (either VMs, Azure Containers, etc.).

=== Tool Installers

We generally prefer to use the Docker Pipeline plugin for system dependencies in the `Jenkinsfile` but it's also possible to use some basic, pre-configured, tool installers.

* `jdk8` A recent OpenJDK 8 version from link:https://github.com/adoptium/[java adoptium]
* `jdk11` A recent OpenJDK 11 version from link:https://github.com/adoptium/[java adoptium]
* `jdk17` A recent OpenJDK 17 version from link:https://github.com/adoptium/[java adoptium]
* `jdk19` A recent OpenJDK 19 version from link:https://github.com/adoptium/[java adoptium]
* `mvn` A recent Maven 3.x version
* `groovy` A recent Groovy 2.x version

== Pipeline plugins

* Pipeline
* Docker Pipeline
* Blue Ocean

== Caching mirrors

https://repo.jenkins-ci.org/nodejs-dist/ and https://repo.jenkins-ci.org/npm-dist/ mirror https://nodejs.org/dist/ and http://registry.npmjs.org/npm/-/, respectively, so these may be used from link:https://github.com/eirslett/frontend-maven-plugin/blob/master/README.md#installing-node-and-npm[frontend-maven-plugin], as happens automatically in the plugin parent POM as of 2.29. (There is currently no mirror for https://github.com/yarnpkg/yarn/releases/download/, the yarn distribution site.)

There is also a mirror of the npm package repository; to use it:

    npm config set registry https://repo.jenkins-ci.org/api/npm/npm/

or

    yarn config set -- --registry https://repo.jenkins-ci.org/api/npm/npm/

Additionally, https://repo.azure.jenkins.io/ mirrors all non-snapshot downloads from https://repo.jenkins-ci.org/. For example, to use this from Maven, pass `-s settings-azure.xml`:

[source,xml]
.settings-azure.xml
----
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <mirrors>
        <mirror>
            <id>azure</id>
            <url>https://repo.azure.jenkins.io/public/</url>
            <mirrorOf>repo.jenkins-ci.org</mirrorOf>
        </mirror>
    </mirrors>
</settings>
----
