= Jenkins on Jenkins

This document covers the services available on
link:https://ci.jenkins.io[ci.jenkins.io]
and our internal `trusted.ci` instance.


=== Node Labels

We use node labels to define capabilities of the nodes in our Jenkins clusters. These are conventional and are to be used
when referencing nodes, e.g. in the `Jenkinsfile`. 

* `linux` : A Linux (Ubuntu 14.04 LTS) instance (alias of `java`)
* `docker` : A Linux (Ubuntu 14.04 LTS) instance with a running Docker daemon
* `windows` : A "stock" Windows 2012 R2 provisioned on Azure
(link:https://azure.microsoft.com/en-us/documentation/articles/cloud-services-sizes-specs/[Standard D3 v2])
* `highram` : A Linux (Ubuntu 14.04 LTS) instance with 4vCPU/28GB RAM 
(link:https://azure.microsoft.com/en-us/documentation/articles/cloud-services-sizes-specs/[Standard A6]). Please avoid unless running ATH or other high-memory capacity instances.
* `puppet` : A Linux (Ubuntu 14.04 LTS) instance that is managed by link:https://github.com/jenkins-infra/jenkins-infra/blob/staging/dist/profile/manifests/buildslave.pp[this Puppet code]


=== Tool Installers

We generally prefer to use the Docker Pipeline plugin for system dependencies in the `Jenkinsfile` but it's also possible to use some basic, pre-configured, tool installers.

* `jdk7` A recent JDK7 version
* `jdk8` A recent JDK8 version
* `mvn` A recent Maven 3.x version
* `groovy` A recent Groovy 2.x version

== Pipeline plugins

* Pipeline
* CloudBees Docker Pipeline
* Blue Ocean

== Caching mirrors

https://repo.jenkins-ci.org/nodejs-dist/ and https://repo.jenkins-ci.org/npm-dist/ mirror https://nodejs.org/dist/ and http://registry.npmjs.org/npm/-/, respectively, so these may be used from link:https://github.com/eirslett/frontend-maven-plugin/blob/master/README.md#installing-node-and-npm[frontend-maven-plugin], as happens automatically in the plugin parent POM as of 2.29. (There is currently no mirror for https://github.com/yarnpkg/yarn/releases/download/, the yarn distribution site.)

There is also a mirror of the npm package repository; to use it:

    npm config set registry https://repo.jenkins-ci.org/api/npm/npm/

or

    yarn config set -- --registry https://repo.jenkins-ci.org/api/npm/npm/

Additionally, https://repo.azure.jenkins.io/ mirrors all non-snapshot downloads from https://repo.jenkins-ci.org/. For example, to use this from Maven, pass `-s settings-azure.xml`:

[source,xml]
.settings-azure.xml
----
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <mirrors>
        <mirror>
            <id>azure</id>
            <url>https://repo.azure.jenkins.io/public/</url>
            <mirrorOf>repo.jenkins-ci.org</mirrorOf>
        </mirror>
    </mirrors>
</settings>
----
