= Jenkins on Jenkins

This document covers the services available on
link:https://ci.jenkins.io[ci.jenkins.io]
and our internal `trusted.ci` instance.


=== Node Labels

We use node labels to define capabilities of the nodes in our Jenkins clusters. These are conventional and are to be used
when referencing nodes, e.g. in the `Jenkinsfile`. 

* `linux` : A Linux (Ubuntu 14.04 LTS) instance (alias of `java`)
* `docker` : A Linux (Ubuntu 14.04 LTS) instance with a running Docker daemon
* `windows` : A "stock" Windows 2012 R2 provisioned on Azure
(link:https://azure.microsoft.com/en-us/documentation/articles/cloud-services-sizes-specs/[Standard D3 v2])
* `highram` : A Linux (Ubuntu 14.04 LTS) instance with 4vCPU/28GB RAM 
(link:https://azure.microsoft.com/en-us/documentation/articles/cloud-services-sizes-specs/[Standard A6]). Please avoid unless running ATH or other high-memory capacity instances.


=== Tool Installers

We generally prefer to use the Docker Pipeline plugin for system dependencies in the `Jenkinsfile` but it's also possible to use some basic, pre-configured, tool installers.

* `jdk7` A recent JDK7 version
* `jdk8` A recent JDK8 version
* `mvn` A recent Maven 3.x version
* `groovy` A recent Groovy 2.x version

== Pipeline plugins

* Pipeine
* CloudBees Docker Pipeline
* Blue Ocean
